format = """
$username\
$directory\
$kubernetes\
$aws\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$time\
$os\
$character
"""

[character]
success_symbol = "\n[â¯](bold green)"
error_symbol = "\n[âœ–](bold red)"

[cmd_duration]
min_time = 500
format = "[$duration](bold yellow) "

[directory]
truncation_length = 4
truncation_symbol = "â€¦/"
truncate_to_repo = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[os]
disabled = false

[username]
style_user = "bold blue"

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[git_branch]
symbol = "ï˜ "
format = "[\\[$symbol$branch\\]]($style) "

[golang]
symbol = "î˜§ "
format = "[\\[$symbol($version )\\]]($style) "

[hostname]
style = "bold green"

[kubernetes]
symbol = "ó±ƒ¾ "
format = 'on [ó±ƒ¾ $context( \($namespace\))](bold bright-green) '
disabled = false

[aws]
format = "on [$symbol$profile( $region)]($style) "
style = "bold Yellow"
symbol = "â˜ï¸ "

[fill]
symbol = ' '

[time]
disabled = false
format = 'ğŸ•™[ $time ]($style)'
time_format = '%T'
